Repository SmileyFaceZ/KU-Hub, pull requests merged in 2023-11, with the labels that each got.

#28 Login fontend
  kuhub/static/authentication_stylesheet.css
  kuhub/static/images/login-bg.jpg
  kuhub/static/images/logo.png
  kuhub/templates/account/login.html
  kuhub/templates/account/logout.html
  kuhub/templates/account/signup.html
  kuhub/templates/socialaccount/login.html
Labels: Merge to main

#42 Solve conflict like dislike
  kuhub/migrations/0007_merge_20231111_2228.py
  kuhub/templates/kuhub/summary.html
  kuhub/views.py
Labels: bug

#71 Feature subject tags
  kuhub/migrations/0002_post_subject.py
  kuhub/models/post.py
  kuhub/templates/base.html
  kuhub/templates/kuhub/gened_list.html
  kuhub/templates/kuhub/review.html
  kuhub/templates/kuhub/subject_detail.html
  kuhub/templates/kuhub/summary.html
  kuhub/urls.py
  kuhub/views.py
Labels: Features, Iteration5
